route:
 group_by: [cluster]
 # If an alert isn't caught by a route, send it slack.
 receiver: slack_general
 routes:
  # Send severity=slack alerts to slack.
  - match:
      severity: slack
    receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - api_url: '<YOUR_API_URL>'
    text: "{{ .CommonAnnotations.description }}"
    username: 'Prometheus'
    channel: '#<YOUR_ALERT_CHANNEL>'
    send_resolved: true
