{
 "title": "SSL Proxy Metrics",
 "description": "Visualize Traefik Health Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "Timeclock Backend",
   "type": "singlestat",
   "description": "Backend",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "traefik_backend_server_up{backend=\"timeclock-internal\",url=\"http://sir_accufund\"}"
    }
   ]
  },
  {
   "title": "Timeclock Backend",
   "type": "singlestat",
   "description": "Backend",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "traefik_backend_server_up{backend=\"helpdesk-internal\",url=\"http://10.0.20.15\"}"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 4 },
   "targets": [
    { "expr": "traefik_backend_server_up" }
   ]
  },
  { "title": "Last 10 Minutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "traefik_backend_request_duration_seconds_sum",
     "legendFormat": "{{code}} {{method}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Timeclock HTTP Codes",
   "type": "graph",
   "description": "We want 200's, anything else should be investigated",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_entrypoint_requests_total",
     "legendFormat": "{{code}} {{method}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Total Status Code Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "traefik_entrypoint_requests_total{code=\"502\",entrypoint=\"https\",method=\"POST\",protocol=\"http\"}",
     "legendFormat": "{{code}} from:{{entrypoint}} to:{{protocol}} {{method}}"
    },
    {
     "expr": "traefik_entrypoint_requests_total{code=\"200\",entrypoint=\"https\",method=\"GET\",protocol=\"http\"}",
     "legendFormat": "{{code}} from:{{entrypoint}} to:{{protocol}} {{method}}"
    },
    {
     "expr": "traefik_entrypoint_requests_total{code=\"200\",entrypoint=\"http\",method=\"GET\",protocol=\"http\"}",
     "legendFormat": "{{code}} from:{{entrypoint}} to:{{protocol}} {{method}}"
    }
   ]
  },
  {
   "title": "Backend Request Duration",
   "type": "graph",
   "description": "Accufund Employee Portal Request Duration - Requests to and from sir_accufund",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "traefik_backend_request_duration_seconds_sum",
     "legendFormat": "{{code}} {{method}} {{protocol}} "
    }
   ]
  },
  { "title": "Last Hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } }
 ]
}